# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'deploy') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set outputs
        id: slide
        run: |
          echo "::set-output name=name::$(echo '${{ github.event.head_commit.message }}' | cut -d' ' -f 2)"
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Build
        run: |
          npm install
          cp ./contents/${{ steps.slide.outputs.name }}.md .
          npm run build -- ${{ steps.slide.outputs.name }}.md -o ./public/${{ steps.slide.outputs.name }}/ --base /slides/${{ steps.slide.outputs.name }}
          rm -f ${{ steps.slide.outputs.name }}.md
      - name: Add link to index.html
        id: add_link
        run: |
          if [ -z "$(grep ${{ steps.slide.outputs.name }} public/index.md)" ]; then
            echo '- https://skanehira.github.io/slides/${{ steps.slide.outputs.name }}' >> public/index.md
            npx marked -o public/index.html -i public/index.md
          fi
          echo "::set-output name=diff::$(git diff --stat ./public/index.md)"
      - name: Commit changes
        if: ${{ steps.add_link.diff != '' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: add ${{ steps.slide.outputs.name }} link"
          file_pattern: public/index.md
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
          keep_files: true
